/**
 * Embedded Words Data
 * This file contains all dictionary data to avoid fetch issues with local files
 */

const WORDS_DATA = {
  version: "1.0.0",
  lastUpdated: "2025-01-15",
  levelInfo: {
    A1: {
      title: "Level A1: Absolute Beginner",
      desc: "Essential vocabulary for daily life, greetings, family, numbers, and basic needs.",
    },
    A2: {
      title: "Level A2: Elementary",
      desc: "Vocabulary for routine tasks, travel, work, and describing your environment.",
    },
    B1: {
      title: "Level B1: Intermediate",
      desc: "Express opinions, discuss familiar topics, describe experiences and events.",
    },
    B2: {
      title: "Level B2: Upper Intermediate",
      desc: "Complex texts, technical discussions, and spontaneous fluent interaction.",
    },
  },
  words: [
    {
      id: "a1-greetings-001",
      de: "Hallo",
      pro_en: "hah-loh",
      pro_ar: "هالو",
      en: "Hello",
      ar: "مرحباً",
      example_de: "Hallo, wie geht es dir?",
      example_ar: "مرحباً، كيف حالك؟",
      pos: "expression",
      category: "greetings",
      level: "A1",
      tags: ["basic", "everyday", "formal", "informal"],
      audio: null,
    },
    {
      id: "a1-greetings-002",
      de: "Guten Morgen",
      pro_en: "goo-ten mor-gen",
      pro_ar: "غوتن مورغن",
      en: "Good morning",
      ar: "صباح الخير",
      example_de: "Guten Morgen! Hast du gut geschlafen?",
      example_ar: "صباح الخير! هل نمت جيداً؟",
      pos: "expression",
      category: "greetings",
      level: "A1",
      tags: ["basic", "everyday", "formal", "morning"],
      audio: null,
    },
    {
      id: "a1-greetings-003",
      de: "Guten Tag",
      pro_en: "goo-ten tahg",
      pro_ar: "غوتن تاغ",
      en: "Good day",
      ar: "يوم سعيد",
      example_de: "Guten Tag, mein Name ist Müller.",
      example_ar: "يوم سعيد، اسمي مولر.",
      pos: "expression",
      category: "greetings",
      level: "A1",
      tags: ["basic", "everyday", "formal"],
      audio: null,
    },
    {
      id: "a1-greetings-004",
      de: "Guten Abend",
      pro_en: "goo-ten ah-bent",
      pro_ar: "غوتن أبند",
      en: "Good evening",
      ar: "مساء الخير",
      example_de: "Guten Abend! Wie war dein Tag?",
      example_ar: "مساء الخير! كيف كان يومك؟",
      pos: "expression",
      category: "greetings",
      level: "A1",
      tags: ["basic", "everyday", "formal", "evening"],
      audio: null,
    },
    {
      id: "a1-greetings-005",
      de: "Gute Nacht",
      pro_en: "goo-tuh nakht",
      pro_ar: "غوتة ناخت",
      en: "Good night",
      ar: "تصبح على خير",
      example_de: "Gute Nacht! Schlaf gut.",
      example_ar: "تصبح على خير! نم جيداً.",
      pos: "expression",
      category: "greetings",
      level: "A1",
      tags: ["basic", "everyday", "farewell", "night"],
      audio: null,
    },
    {
      id: "a1-greetings-006",
      de: "Danke",
      pro_en: "dahn-kuh",
      pro_ar: "دانكه",
      en: "Thank you",
      ar: "شكراً",
      example_de: "Danke für das Geschenk.",
      example_ar: "شكراً على الهدية.",
      pos: "expression",
      category: "greetings",
      level: "A1",
      tags: ["basic", "everyday", "polite"],
      audio: null,
    },
    {
      id: "a1-greetings-007",
      de: "Bitte",
      pro_en: "bi-tuh",
      pro_ar: "بيته",
      en: "Please / You're welcome",
      ar: "من فضلك / عفواً",
      example_de: "Einen Kaffee, bitte.",
      example_ar: "قهوة، من فضلك.",
      pos: "expression",
      category: "greetings",
      level: "A1",
      tags: ["basic", "everyday", "polite"],
      audio: null,
    },
    {
      id: "a1-greetings-008",
      de: "Auf Wiedersehen",
      pro_en: "owf vee-der-zayn",
      pro_ar: "أوف فيدر زين",
      en: "Goodbye",
      ar: "إلى اللقاء",
      example_de: "Auf Wiedersehen, bis morgen!",
      example_ar: "إلى اللقاء، إلى الغد!",
      pos: "expression",
      category: "greetings",
      level: "A1",
      tags: ["basic", "everyday", "formal", "farewell"],
      audio: null,
    },
    {
      id: "a1-greetings-009",
      de: "Tschüss",
      pro_en: "chews",
      pro_ar: "تشوس",
      en: "Bye",
      ar: "وداعاً",
      example_de: "Tschüss! Bis bald.",
      example_ar: "وداعاً! إلى قريب.",
      pos: "expression",
      category: "greetings",
      level: "A1",
      tags: ["basic", "everyday", "informal", "farewell"],
      audio: null,
    },
    {
      id: "a1-greetings-010",
      de: "Ja",
      pro_en: "ya",
      pro_ar: "يا",
      en: "Yes",
      ar: "نعم",
      example_de: "Ja, ich komme mit.",
      example_ar: "نعم، سأأتي معك.",
      pos: "expression",
      category: "greetings",
      level: "A1",
      tags: ["basic", "everyday"],
      audio: null,
    },
    {
      id: "a1-greetings-011",
      de: "Nein",
      pro_en: "nine",
      pro_ar: "ناين",
      en: "No",
      ar: "لا",
      example_de: "Nein, ich habe keine Zeit.",
      example_ar: "لا، ليس لدي وقت.",
      pos: "expression",
      category: "greetings",
      level: "A1",
      tags: ["basic", "everyday"],
      audio: null,
    },
    {
      id: "a1-greetings-012",
      de: "Wie geht es Ihnen?",
      pro_en: "vee gayt es ee-nen",
      pro_ar: "في غيت إس إينن",
      en: "How are you? (formal)",
      ar: "كيف حالك؟ (رسمي)",
      example_de: "Wie geht es Ihnen heute?",
      example_ar: "كيف حالك اليوم؟",
      pos: "expression",
      category: "greetings",
      level: "A1",
      tags: ["basic", "everyday", "formal"],
      audio: null,
    },
    {
      id: "a1-greetings-013",
      de: "Wie geht es dir?",
      pro_en: "vee gayt es deer",
      pro_ar: "في غيت إس دير",
      en: "How are you? (informal)",
      ar: "كيف حالك؟ (غير رسمي)",
      example_de: "Hey! Wie geht es dir?",
      example_ar: "مرحباً! كيف حالك؟",
      pos: "expression",
      category: "greetings",
      level: "A1",
      tags: ["basic", "everyday", "informal"],
      audio: null,
    },
    {
      id: "a1-greetings-014",
      de: "Entschuldigung",
      pro_en: "ent-shool-di-goong",
      pro_ar: "إنتشولديغونغ",
      en: "Excuse me / Sorry",
      ar: "عذراً / آسف",
      example_de: "Entschuldigung, wo ist der Bahnhof?",
      example_ar: "عذراً، أين محطة القطار؟",
      pos: "expression",
      category: "greetings",
      level: "A1",
      tags: ["basic", "everyday", "polite"],
      audio: null,
    },
    {
      id: "a1-numbers-001",
      de: "null",
      pro_en: "nool",
      pro_ar: "نول",
      en: "zero",
      ar: "صفر",
      example_de: "Die Temperatur ist null Grad.",
      example_ar: "درجة الحرارة صفر.",
      pos: "noun",
      category: "numbers",
      level: "A1",
      tags: ["basic", "numbers", "counting"],
      audio: null,
    },
    {
      id: "a1-numbers-002",
      de: "eins",
      pro_en: "eyns",
      pro_ar: "آينس",
      en: "one",
      ar: "واحد",
      example_de: "Ich habe eine Katze.",
      example_ar: "لدي قطة واحدة.",
      pos: "noun",
      category: "numbers",
      level: "A1",
      tags: ["basic", "numbers", "counting"],
      audio: null,
    },
    {
      id: "a1-numbers-003",
      de: "zwei",
      pro_en: "tsvai",
      pro_ar: "تسفاي",
      en: "two",
      ar: "اثنان",
      example_de: "Zwei Kaffee, bitte.",
      example_ar: "قهوتان، من فضلك.",
      pos: "noun",
      category: "numbers",
      level: "A1",
      tags: ["basic", "numbers", "counting"],
      audio: null,
    },
    {
      id: "a1-numbers-004",
      de: "drei",
      pro_en: "dry",
      pro_ar: "دراي",
      en: "three",
      ar: "ثلاثة",
      example_de: "Aller guten Dinge sind drei.",
      example_ar: "كل الأشياء الجيدة تأتي ثلاثية.",
      pos: "noun",
      category: "numbers",
      level: "A1",
      tags: ["basic", "numbers", "counting"],
      audio: null,
    },
    {
      id: "a1-numbers-005",
      de: "vier",
      pro_en: "feer",
      pro_ar: "فير",
      en: "four",
      ar: "أربعة",
      example_de: "Wir sind vier Personen.",
      example_ar: "نحن أربعة أشخاص.",
      pos: "noun",
      category: "numbers",
      level: "A1",
      tags: ["basic", "numbers", "counting"],
      audio: null,
    },
    {
      id: "a1-numbers-006",
      de: "fünf",
      pro_en: "fewnf",
      pro_ar: "فونف",
      en: "five",
      ar: "خمسة",
      example_de: "Ich habe fünf Finger.",
      example_ar: "لدي خمس أصابع.",
      pos: "noun",
      category: "numbers",
      level: "A1",
      tags: ["basic", "numbers", "counting"],
      audio: null,
    },
    {
      id: "a1-numbers-007",
      de: "sechs",
      pro_en: "zeks",
      pro_ar: "زيكس",
      en: "six",
      ar: "ستة",
      example_de: "Ein Würfel hat sechs Seiten.",
      example_ar: "للنرد ستة أوجه.",
      pos: "noun",
      category: "numbers",
      level: "A1",
      tags: ["basic", "numbers", "counting"],
      audio: null,
    },
    {
      id: "a1-numbers-008",
      de: "sieben",
      pro_en: "zee-ben",
      pro_ar: "زيبن",
      en: "seven",
      ar: "سبعة",
      example_de: "Eine Woche hat sieben Tage.",
      example_ar: "الأسبوع به سبعة أيام.",
      pos: "noun",
      category: "numbers",
      level: "A1",
      tags: ["basic", "numbers", "counting"],
      audio: null,
    },
    {
      id: "a1-numbers-009",
      de: "acht",
      pro_en: "akht",
      pro_ar: "آخت",
      en: "eight",
      ar: "ثمانية",
      example_de: "Die Schule beginnt um acht Uhr.",
      example_ar: "المدرسة تبدأ في الثامنة.",
      pos: "noun",
      category: "numbers",
      level: "A1",
      tags: ["basic", "numbers", "counting"],
      audio: null,
    },
    {
      id: "a1-numbers-010",
      de: "neun",
      pro_en: "noyn",
      pro_ar: "نوين",
      en: "nine",
      ar: "تسعة",
      example_de: "Eine Katze hat neun Leben.",
      example_ar: "للقطة تسعة أرواح.",
      pos: "noun",
      category: "numbers",
      level: "A1",
      tags: ["basic", "numbers", "counting"],
      audio: null,
    },
    {
      id: "a1-numbers-011",
      de: "zehn",
      pro_en: "tsayn",
      pro_ar: "تسين",
      en: "ten",
      ar: "عشرة",
      example_de: "Es ist zehn Uhr.",
      example_ar: "الساعة العاشرة.",
      pos: "noun",
      category: "numbers",
      level: "A1",
      tags: ["basic", "numbers", "counting"],
      audio: null,
    },
    {
      id: "a1-numbers-012",
      de: "zwanzig",
      pro_en: "tsvan-tsig",
      pro_ar: "تسفانتسيغ",
      en: "twenty",
      ar: "عشرون",
      example_de: "Ich bin zwanzig Jahre alt.",
      example_ar: "عمري عشرون سنة.",
      pos: "noun",
      category: "numbers",
      level: "A1",
      tags: ["basic", "numbers", "counting"],
      audio: null,
    },
    {
      id: "a1-numbers-013",
      de: "hundert",
      pro_en: "hoon-dert",
      pro_ar: "هوندرت",
      en: "hundred",
      ar: "مائة",
      example_de: "Das kostet hundert Euro.",
      example_ar: "هذا يكلف مائة يورو.",
      pos: "noun",
      category: "numbers",
      level: "A1",
      tags: ["basic", "numbers", "counting"],
      audio: null,
    },
    {
      id: "a1-family-001",
      de: "die Familie",
      pro_en: "dee fah-mee-lyuh",
      pro_ar: "دي فاميليا",
      en: "Family",
      ar: "العائلة",
      example_de: "Meine Familie wohnt in Berlin.",
      example_ar: "عائلتي تعيش في برلين.",
      pos: "noun",
      category: "family",
      level: "A1",
      tags: ["basic", "family", "people"],
      audio: null,
    },
    {
      id: "a1-family-002",
      de: "der Vater",
      pro_en: "dair fah-ter",
      pro_ar: "دير فاتر",
      en: "Father",
      ar: "الأب",
      example_de: "Mein Vater arbeitet bei der Bank.",
      example_ar: "أبي يعمل في البنك.",
      pos: "noun",
      category: "family",
      level: "A1",
      tags: ["basic", "family", "people"],
      audio: null,
    },
    {
      id: "a1-family-003",
      de: "die Mutter",
      pro_en: "dee moo-ter",
      pro_ar: "دي موتر",
      en: "Mother",
      ar: "الأم",
      example_de: "Meine Mutter kocht sehr gut.",
      example_ar: "أمي تطبخ جيداً جداً.",
      pos: "noun",
      category: "family",
      level: "A1",
      tags: ["basic", "family", "people"],
      audio: null,
    },
    {
      id: "a1-family-004",
      de: "der Bruder",
      pro_en: "dair broo-der",
      pro_ar: "دير برودر",
      en: "Brother",
      ar: "الأخ",
      example_de: "Mein Bruder ist älter als ich.",
      example_ar: "أخي أكبر مني.",
      pos: "noun",
      category: "family",
      level: "A1",
      tags: ["basic", "family", "people"],
      audio: null,
    },
    {
      id: "a1-family-005",
      de: "die Schwester",
      pro_en: "dee shves-ter",
      pro_ar: "دي شفيستر",
      en: "Sister",
      ar: "الأخت",
      example_de: "Meine Schwester studiert Medizin.",
      example_ar: "أختي تدرس الطب.",
      pos: "noun",
      category: "family",
      level: "A1",
      tags: ["basic", "family", "people"],
      audio: null,
    },
    {
      id: "a1-family-006",
      de: "der Sohn",
      pro_en: "dair zohn",
      pro_ar: "دير زون",
      en: "Son",
      ar: "الابن",
      example_de: "Mein Sohn geht in die Schule.",
      example_ar: "ابني يذهب إلى المدرسة.",
      pos: "noun",
      category: "family",
      level: "A1",
      tags: ["basic", "family", "people"],
      audio: null,
    },
    {
      id: "a1-family-007",
      de: "die Tochter",
      pro_en: "dee tokh-ter",
      pro_ar: "دي توختر",
      en: "Daughter",
      ar: "الابنة",
      example_de: "Meine Tochter ist sehr klug.",
      example_ar: "ابنتي ذكية جداً.",
      pos: "noun",
      category: "family",
      level: "A1",
      tags: ["basic", "family", "people"],
      audio: null,
    },
    {
      id: "a1-family-008",
      de: "der Großvater",
      pro_en: "dair grohs-fah-ter",
      pro_ar: "دير غروسفاتر",
      en: "Grandfather",
      ar: "الجد",
      example_de: "Mein Großvater ist 80 Jahre alt.",
      example_ar: "جدي عمره 80 سنة.",
      pos: "noun",
      category: "family",
      level: "A1",
      tags: ["basic", "family", "people"],
      audio: null,
    },
    {
      id: "a1-family-009",
      de: "die Großmutter",
      pro_en: "dee grohs-moo-ter",
      pro_ar: "دي غروسموتر",
      en: "Grandmother",
      ar: "الجدة",
      example_de: "Meine Großmutter backt Kuchen.",
      example_ar: "جدتي تخبز الكعك.",
      pos: "noun",
      category: "family",
      level: "A1",
      tags: ["basic", "family", "people"],
      audio: null,
    },
    {
      id: "a1-food-001",
      de: "das Essen",
      pro_en: "das es-sen",
      pro_ar: "داس إيسن",
      en: "Food",
      ar: "الطعام",
      example_de: "Das Essen schmeckt gut.",
      example_ar: "الطعام لذيذ.",
      pos: "noun",
      category: "food",
      level: "A1",
      tags: ["basic", "food", "everyday"],
      audio: null,
    },
    {
      id: "a1-food-002",
      de: "das Wasser",
      pro_en: "das vas-ser",
      pro_ar: "داس فاسر",
      en: "Water",
      ar: "الماء",
      example_de: "Ich trinke gern Wasser.",
      example_ar: "أحب شرب الماء.",
      pos: "noun",
      category: "food",
      level: "A1",
      tags: ["basic", "food", "drinks"],
      audio: null,
    },
    {
      id: "a1-food-003",
      de: "das Brot",
      pro_en: "das broht",
      pro_ar: "داس بروت",
      en: "Bread",
      ar: "الخبز",
      example_de: "Das Brot ist frisch.",
      example_ar: "الخبز طازج.",
      pos: "noun",
      category: "food",
      level: "A1",
      tags: ["basic", "food"],
      audio: null,
    },
    {
      id: "a1-food-004",
      de: "der Kaffee",
      pro_en: "dair kaf-fay",
      pro_ar: "دير كافي",
      en: "Coffee",
      ar: "القهوة",
      example_de: "Ich brauche Kaffee.",
      example_ar: "أحتاج قهوة.",
      pos: "noun",
      category: "food",
      level: "A1",
      tags: ["basic", "food", "drinks"],
      audio: null,
    },
    {
      id: "a1-food-005",
      de: "der Tee",
      pro_en: "dair tay",
      pro_ar: "دير تاي",
      en: "Tea",
      ar: "الشاي",
      example_de: "Möchtest du Tee?",
      example_ar: "هل تريد شاي؟",
      pos: "noun",
      category: "food",
      level: "A1",
      tags: ["basic", "food", "drinks"],
      audio: null,
    },
    {
      id: "a1-food-006",
      de: "die Milch",
      pro_en: "dee milkh",
      pro_ar: "دي ميلخ",
      en: "Milk",
      ar: "الحليب",
      example_de: "Ich trinke Milch zum Frühstück.",
      example_ar: "أشرب الحليب في الفطور.",
      pos: "noun",
      category: "food",
      level: "A1",
      tags: ["basic", "food", "drinks"],
      audio: null,
    },
    {
      id: "a1-food-007",
      de: "der Apfel",
      pro_en: "dair ap-fel",
      pro_ar: "دير أبفل",
      en: "Apple",
      ar: "التفاحة",
      example_de: "Der Apfel ist rot.",
      example_ar: "التفاحة حمراء.",
      pos: "noun",
      category: "food",
      level: "A1",
      tags: ["basic", "food", "fruit"],
      audio: null,
    },
    {
      id: "a1-food-008",
      de: "das Fleisch",
      pro_en: "das flysh",
      pro_ar: "داس فلايش",
      en: "Meat",
      ar: "اللحم",
      example_de: "Ich esse kein Fleisch.",
      example_ar: "أنا لا آكل اللحم.",
      pos: "noun",
      category: "food",
      level: "A1",
      tags: ["basic", "food"],
      audio: null,
    },
    {
      id: "a1-food-009",
      de: "das Gemüse",
      pro_en: "das ge-mew-zuh",
      pro_ar: "داس غيموزة",
      en: "Vegetables",
      ar: "الخضروات",
      example_de: "Gemüse ist gesund.",
      example_ar: "الخضروات صحية.",
      pos: "noun",
      category: "food",
      level: "A1",
      tags: ["basic", "food"],
      audio: null,
    },
    {
      id: "a1-colors-001",
      de: "rot",
      pro_en: "roht",
      pro_ar: "روت",
      en: "red",
      ar: "أحمر",
      example_de: "Das Auto ist rot.",
      example_ar: "السيارة حمراء.",
      pos: "adj",
      category: "colors",
      level: "A1",
      tags: ["basic", "colors", "descriptive"],
      audio: null,
    },
    {
      id: "a1-colors-002",
      de: "blau",
      pro_en: "blow",
      pro_ar: "بلاو",
      en: "blue",
      ar: "أزرق",
      example_de: "Der Himmel ist blau.",
      example_ar: "السماء زرقاء.",
      pos: "adj",
      category: "colors",
      level: "A1",
      tags: ["basic", "colors", "descriptive"],
      audio: null,
    },
    {
      id: "a1-colors-003",
      de: "grün",
      pro_en: "grewn",
      pro_ar: "غرون",
      en: "green",
      ar: "أخضر",
      example_de: "Das Gras ist grün.",
      example_ar: "العشب أخضر.",
      pos: "adj",
      category: "colors",
      level: "A1",
      tags: ["basic", "colors", "descriptive"],
      audio: null,
    },
    {
      id: "a1-colors-004",
      de: "gelb",
      pro_en: "gelp",
      pro_ar: "غيلب",
      en: "yellow",
      ar: "أصفر",
      example_de: "Die Sonne ist gelb.",
      example_ar: "الشمس صفراء.",
      pos: "adj",
      category: "colors",
      level: "A1",
      tags: ["basic", "colors", "descriptive"],
      audio: null,
    },
    {
      id: "a1-colors-005",
      de: "schwarz",
      pro_en: "shvarts",
      pro_ar: "شفارتس",
      en: "black",
      ar: "أسود",
      example_de: "Die Katze ist schwarz.",
      example_ar: "القطة سوداء.",
      pos: "adj",
      category: "colors",
      level: "A1",
      tags: ["basic", "colors", "descriptive"],
      audio: null,
    },
    {
      id: "a1-colors-006",
      de: "weiß",
      pro_en: "vice",
      pro_ar: "فايس",
      en: "white",
      ar: "أبيض",
      example_de: "Der Schnee ist weiß.",
      example_ar: "الثلج أبيض.",
      pos: "adj",
      category: "colors",
      level: "A1",
      tags: ["basic", "colors", "descriptive"],
      audio: null,
    },
    {
      id: "a1-colors-007",
      de: "orange",
      pro_en: "oh-rahn-zhuh",
      pro_ar: "أورانج",
      en: "orange",
      ar: "برتقالي",
      example_de: "Die Orange ist orange.",
      example_ar: "البرتقالة برتقالية.",
      pos: "adj",
      category: "colors",
      level: "A1",
      tags: ["basic", "colors", "descriptive"],
      audio: null,
    },
    {
      id: "a1-colors-008",
      de: "braun",
      pro_en: "brown",
      pro_ar: "براون",
      en: "brown",
      ar: "بني",
      example_de: "Der Hund ist braun.",
      example_ar: "الكلب بني.",
      pos: "adj",
      category: "colors",
      level: "A1",
      tags: ["basic", "colors", "descriptive"],
      audio: null,
    },
    {
      id: "a1-verbs-001",
      de: "sein",
      pro_en: "zine",
      pro_ar: "زاين",
      en: "to be",
      ar: "يكون",
      example_de: "Ich bin Student.",
      example_ar: "أنا طالب.",
      pos: "verb",
      category: "verbs",
      level: "A1",
      tags: ["basic", "verbs", "essential"],
      audio: null,
    },
    {
      id: "a1-verbs-002",
      de: "haben",
      pro_en: "hah-ben",
      pro_ar: "هابن",
      en: "to have",
      ar: "يملك",
      example_de: "Ich habe ein Auto.",
      example_ar: "لدي سيارة.",
      pos: "verb",
      category: "verbs",
      level: "A1",
      tags: ["basic", "verbs", "essential"],
      audio: null,
    },
    {
      id: "a1-verbs-003",
      de: "gehen",
      pro_en: "gay-en",
      pro_ar: "غيين",
      en: "to go",
      ar: "يذهب",
      example_de: "Ich gehe zur Schule.",
      example_ar: "أذهب إلى المدرسة.",
      pos: "verb",
      category: "verbs",
      level: "A1",
      tags: ["basic", "verbs", "movement"],
      audio: null,
    },
    {
      id: "a1-verbs-004",
      de: "kommen",
      pro_en: "kom-men",
      pro_ar: "كومن",
      en: "to come",
      ar: "يأتي",
      example_de: "Er kommt aus Deutschland.",
      example_ar: "هو يأتي من ألمانيا.",
      pos: "verb",
      category: "verbs",
      level: "A1",
      tags: ["basic", "verbs", "movement"],
      audio: null,
    },
    {
      id: "a1-verbs-005",
      de: "machen",
      pro_en: "makh-en",
      pro_ar: "ماخن",
      en: "to do / make",
      ar: "يفعل / يصنع",
      example_de: "Was machst du heute?",
      example_ar: "ماذا تفعل اليوم؟",
      pos: "verb",
      category: "verbs",
      level: "A1",
      tags: ["basic", "verbs", "everyday"],
      audio: null,
    },
    {
      id: "a1-verbs-006",
      de: "essen",
      pro_en: "es-sen",
      pro_ar: "إسن",
      en: "to eat",
      ar: "يأكل",
      example_de: "Ich esse gern Pizza.",
      example_ar: "أحب أكل البيتزا.",
      pos: "verb",
      category: "verbs",
      level: "A1",
      tags: ["basic", "verbs", "food"],
      audio: null,
    },
    {
      id: "a1-verbs-007",
      de: "trinken",
      pro_en: "trin-ken",
      pro_ar: "ترينكن",
      en: "to drink",
      ar: "يشرب",
      example_de: "Ich trinke Wasser.",
      example_ar: "أشرب الماء.",
      pos: "verb",
      category: "verbs",
      level: "A1",
      tags: ["basic", "verbs", "food"],
      audio: null,
    },
    {
      id: "a1-verbs-008",
      de: "sprechen",
      pro_en: "shpre-khen",
      pro_ar: "شبريخن",
      en: "to speak",
      ar: "يتحدث",
      example_de: "Ich spreche Deutsch.",
      example_ar: "أتحدث الألمانية.",
      pos: "verb",
      category: "verbs",
      level: "A1",
      tags: ["basic", "verbs", "communication"],
      audio: null,
    },
    {
      id: "a1-verbs-009",
      de: "lernen",
      pro_en: "ler-nen",
      pro_ar: "ليرنن",
      en: "to learn",
      ar: "يتعلم",
      example_de: "Ich lerne Deutsch.",
      example_ar: "أتعلم الألمانية.",
      pos: "verb",
      category: "verbs",
      level: "A1",
      tags: ["basic", "verbs", "education"],
      audio: null,
    },
    {
      id: "a1-verbs-010",
      de: "wohnen",
      pro_en: "voh-nen",
      pro_ar: "فونن",
      en: "to live (reside)",
      ar: "يسكن",
      example_de: "Ich wohne in Berlin.",
      example_ar: "أسكن في برلين.",
      pos: "verb",
      category: "verbs",
      level: "A1",
      tags: ["basic", "verbs", "everyday"],
      audio: null,
    },
    {
      id: "a1-places-001",
      de: "das Haus",
      pro_en: "das house",
      pro_ar: "داس هاوس",
      en: "House",
      ar: "المنزل",
      example_de: "Das Haus ist groß.",
      example_ar: "المنزل كبير.",
      pos: "noun",
      category: "places",
      level: "A1",
      tags: ["basic", "places", "home"],
      audio: null,
    },
    {
      id: "a1-places-002",
      de: "die Schule",
      pro_en: "dee shoo-luh",
      pro_ar: "دي شولة",
      en: "School",
      ar: "المدرسة",
      example_de: "Die Schule beginnt um 8 Uhr.",
      example_ar: "المدرسة تبدأ في الساعة 8.",
      pos: "noun",
      category: "places",
      level: "A1",
      tags: ["basic", "places", "education"],
      audio: null,
    },
    {
      id: "a1-places-003",
      de: "der Bahnhof",
      pro_en: "dair bahn-hof",
      pro_ar: "دير بانهوف",
      en: "Train station",
      ar: "محطة القطار",
      example_de: "Der Zug fährt vom Bahnhof ab.",
      example_ar: "القطار يغادر من المحطة.",
      pos: "noun",
      category: "places",
      level: "A1",
      tags: ["basic", "places", "travel"],
      audio: null,
    },
    {
      id: "a1-places-004",
      de: "das Restaurant",
      pro_en: "das res-toh-rahng",
      pro_ar: "داس ريستوران",
      en: "Restaurant",
      ar: "المطعم",
      example_de: "Das Restaurant ist teuer.",
      example_ar: "المطعم غالي.",
      pos: "noun",
      category: "places",
      level: "A1",
      tags: ["basic", "places", "food"],
      audio: null,
    },
    {
      id: "a1-places-005",
      de: "der Supermarkt",
      pro_en: "dair zoo-per-markt",
      pro_ar: "دير زوبرماركت",
      en: "Supermarket",
      ar: "السوبرماركت",
      example_de: "Ich kaufe im Supermarkt ein.",
      example_ar: "أتسوق في السوبرماركت.",
      pos: "noun",
      category: "places",
      level: "A1",
      tags: ["basic", "places", "shopping"],
      audio: null,
    },
    {
      id: "a1-professions-001",
      de: "der Arzt",
      pro_en: "dair artst",
      pro_ar: "دير آرتست",
      en: "Doctor",
      ar: "الطبيب",
      example_de: "Der Arzt hilft kranken Menschen.",
      example_ar: "الطبيب يساعد المرضى.",
      pos: "noun",
      category: "professions",
      level: "A1",
      tags: ["basic", "professions", "health"],
      audio: null,
    },
    {
      id: "a1-professions-002",
      de: "der Lehrer",
      pro_en: "dair lay-rer",
      pro_ar: "دير ليرر",
      en: "Teacher",
      ar: "المعلم",
      example_de: "Der Lehrer erklärt die Grammatik.",
      example_ar: "المعلم يشرح القواعد.",
      pos: "noun",
      category: "professions",
      level: "A1",
      tags: ["basic", "professions", "education"],
      audio: null,
    },
    {
      id: "a1-professions-003",
      de: "der Ingenieur",
      pro_en: "dair in-gen-yur",
      pro_ar: "دير إنجينيور",
      en: "Engineer",
      ar: "المهندس",
      example_de: "Der Ingenieur baut Brücken.",
      example_ar: "المهندس يبني الجسور.",
      pos: "noun",
      category: "professions",
      level: "A1",
      tags: ["basic", "professions", "work"],
      audio: null,
    },
    {
      id: "a1-professions-004",
      de: "der Koch",
      pro_en: "dair kokh",
      pro_ar: "دير كوخ",
      en: "Chef / Cook",
      ar: "الطباخ",
      example_de: "Der Koch macht das Essen.",
      example_ar: "الطباخ يحضر الطعام.",
      pos: "noun",
      category: "professions",
      level: "A1",
      tags: ["basic", "professions", "food"],
      audio: null,
    },
    {
      id: "a1-clothing-001",
      de: "das Hemd",
      pro_en: "das hempt",
      pro_ar: "داس هيمد",
      en: "Shirt",
      ar: "القميص",
      example_de: "Das Hemd ist blau.",
      example_ar: "القميص أزرق.",
      pos: "noun",
      category: "clothing",
      level: "A1",
      tags: ["basic", "clothing"],
      audio: null,
    },
    {
      id: "a1-clothing-002",
      de: "die Hose",
      pro_en: "dee ho-zuh",
      pro_ar: "دي هوزة",
      en: "Pants",
      ar: "البنطلون",
      example_de: "Die Hose ist zu lang.",
      example_ar: "البنطلون طويل جداً.",
      pos: "noun",
      category: "clothing",
      level: "A1",
      tags: ["basic", "clothing"],
      audio: null,
    },
    {
      id: "a1-clothing-003",
      de: "die Schuhe",
      pro_en: "dee shoo-uh",
      pro_ar: "دي شوه",
      en: "Shoes",
      ar: "الأحذية",
      example_de: "Die Schuhe sind neu.",
      example_ar: "الأحذية جديدة.",
      pos: "noun",
      category: "clothing",
      level: "A1",
      tags: ["basic", "clothing"],
      audio: null,
    },
    {
      id: "a1-clothing-004",
      de: "die Jacke",
      pro_en: "dee yak-uh",
      pro_ar: "دي ياكه",
      en: "Jacket",
      ar: "السترة",
      example_de: "Die Jacke ist warm.",
      example_ar: "السترة دافئة.",
      pos: "noun",
      category: "clothing",
      level: "A1",
      tags: ["basic", "clothing"],
      audio: null,
    },
    {
      id: "a2-verbs-001",
      de: "verstehen",
      pro_en: "fer-shtay-en",
      pro_ar: "فرشتيين",
      en: "to understand",
      ar: "يفهم",
      example_de: "Ich verstehe nicht.",
      example_ar: "أنا لا أفهم.",
      pos: "verb",
      category: "verbs",
      level: "A2",
      tags: ["verbs", "communication"],
      audio: null,
    },
    {
      id: "a2-verbs-002",
      de: "arbeiten",
      pro_en: "ar-by-ten",
      pro_ar: "أربايتن",
      en: "to work",
      ar: "يعمل",
      example_de: "Ich arbeite von Montag bis Freitag.",
      example_ar: "أعمل من الاثنين إلى الجمعة.",
      pos: "verb",
      category: "verbs",
      level: "A2",
      tags: ["verbs", "work"],
      audio: null,
    },
    {
      id: "a2-verbs-003",
      de: "kaufen",
      pro_en: "kow-fen",
      pro_ar: "كاوفن",
      en: "to buy",
      ar: "يشتري",
      example_de: "Ich kaufe ein neues Buch.",
      example_ar: "أشتري كتاباً جديداً.",
      pos: "verb",
      category: "verbs",
      level: "A2",
      tags: ["verbs", "shopping"],
      audio: null,
    },
    {
      id: "a2-verbs-004",
      de: "reisen",
      pro_en: "ry-zen",
      pro_ar: "رايزن",
      en: "to travel",
      ar: "يسافر",
      example_de: "Wir reisen nach Italien.",
      example_ar: "نسافر إلى إيطاليا.",
      pos: "verb",
      category: "verbs",
      level: "A2",
      tags: ["verbs", "travel"],
      audio: null,
    },
    {
      id: "a2-places-001",
      de: "das Krankenhaus",
      pro_en: "das kran-ken-house",
      pro_ar: "داس كرانكنهاوس",
      en: "Hospital",
      ar: "المستشفى",
      example_de: "Sie liegt im Krankenhaus.",
      example_ar: "هي في المستشفى.",
      pos: "noun",
      category: "places",
      level: "A2",
      tags: ["places", "health"],
      audio: null,
    },
    {
      id: "a2-places-002",
      de: "die Universität",
      pro_en: "dee oo-ni-ver-zi-tayt",
      pro_ar: "دي أونيفرزيتيت",
      en: "University",
      ar: "الجامعة",
      example_de: "Ich studiere an der Universität.",
      example_ar: "أدرس في الجامعة.",
      pos: "noun",
      category: "places",
      level: "A2",
      tags: ["places", "education"],
      audio: null,
    },
    {
      id: "a2-places-003",
      de: "das Büro",
      pro_en: "das bew-roh",
      pro_ar: "داس بورو",
      en: "Office",
      ar: "المكتب",
      example_de: "Ich arbeite im Büro.",
      example_ar: "أعمل في المكتب.",
      pos: "noun",
      category: "places",
      level: "A2",
      tags: ["places", "work"],
      audio: null,
    },
    {
      id: "b1-verbs-001",
      de: "beantragen",
      pro_en: "be-an-trah-gen",
      pro_ar: "بيأنتراغن",
      en: "to apply for",
      ar: "يتقدم بطلب",
      example_de: "Ich muss ein Visum beantragen.",
      example_ar: "يجب أن أتقدم بطلب تأشيرة.",
      pos: "verb",
      category: "verbs",
      level: "B1",
      tags: ["verbs", "formal", "administration"],
      audio: null,
    },
    {
      id: "b1-verbs-002",
      de: "entwickeln",
      pro_en: "ent-vik-eln",
      pro_ar: "إنتفيكلن",
      en: "to develop",
      ar: "يطور",
      example_de: "Wir entwickeln eine neue App.",
      example_ar: "نطور تطبيقاً جديداً.",
      pos: "verb",
      category: "verbs",
      level: "B1",
      tags: ["verbs", "work", "technology"],
      audio: null,
    },
    {
      id: "b1-verbs-003",
      de: "empfehlen",
      pro_en: "emp-fay-len",
      pro_ar: "إمبفيلن",
      en: "to recommend",
      ar: "يوصي",
      example_de: "Ich empfehle dieses Restaurant.",
      example_ar: "أوصي بهذا المطعم.",
      pos: "verb",
      category: "verbs",
      level: "B1",
      tags: ["verbs", "communication"],
      audio: null,
    },
    {
      id: "b1-places-001",
      de: "das Rathaus",
      pro_en: "das raht-house",
      pro_ar: "داس راتهاوس",
      en: "Town hall",
      ar: "قاعة البلدية",
      example_de: "Das Rathaus ist im Zentrum.",
      example_ar: "قاعة البلدية في المركز.",
      pos: "noun",
      category: "places",
      level: "B1",
      tags: ["places", "city", "administration"],
      audio: null,
    },
    {
      id: "b2-verbs-001",
      de: "berücksichtigen",
      pro_en: "be-ruk-sikh-ti-gen",
      pro_ar: "بيروكزيختيغن",
      en: "to consider / take into account",
      ar: "يأخذ بعين الاعتبار",
      example_de: "Wir müssen alle Faktoren berücksichtigen.",
      example_ar: "يجب أن نأخذ جميع العوامل بعين الاعتبار.",
      pos: "verb",
      category: "verbs",
      level: "B2",
      tags: ["verbs", "formal", "business"],
      audio: null,
    },
    {
      id: "b2-verbs-002",
      de: "voraussetzen",
      pro_en: "for-ows-zet-sen",
      pro_ar: "فوراوسزيتسن",
      en: "to require / presuppose",
      ar: "يفترض مسبقاً",
      example_de: "Diese Stelle setzt Erfahrung voraus.",
      example_ar: "هذه الوظيفة تتطلب خبرة.",
      pos: "verb",
      category: "verbs",
      level: "B2",
      tags: ["verbs", "formal", "work"],
      audio: null,
    },
    {
      id: "b2-verbs-003",
      de: "sich auseinandersetzen",
      pro_en: "zikh ows-eye-nan-der-zet-sen",
      pro_ar: "زيخ أوساينندرزيتسن",
      en: "to deal with / engage with",
      ar: "يتعامل مع",
      example_de: "Man muss sich mit diesem Thema auseinandersetzen.",
      example_ar: "يجب التعامل مع هذا الموضوع.",
      pos: "verb",
      category: "verbs",
      level: "B2",
      tags: ["verbs", "formal", "academic"],
      audio: null,
    },
  ],
}

// Export for use in other modules
if (typeof window !== "undefined") {
  window.WORDS_DATA = WORDS_DATA
}
